name: Trigger auto deployment for smart-kitchen-webapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/smart-kitchen-webapp-AutoDeployTrigger-9ec3385b-f7ab-4bd7-8f1d-bdd0c9d53768.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SMARTKITCHENWEBAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SMARTKITCHENWEBAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SMARTKITCHENWEBAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: SarasKitchenApp/SarasKitchenApp
          _dockerfilePathKey_: SarasKitchenApp/SarasKitchenApp/Dockerfile
          registryUrl: smartkitchenacr.azurecr.io
          registryUsername: ${{ secrets.SMARTKITCHENWEBAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SMARTKITCHENWEBAPP_REGISTRY_PASSWORD }}
          containerAppName: smart-kitchen-webapp
          resourceGroup: SmartKitchen
          imageToBuild: smartkitchenacr.azurecr.io/smart-kitchen-webapp:${{ github.sha }}



